#!/usr/bin/python3
#executar com python3 "nome do arquivo".py
#Pedro Victor Oliveira Carvalho / numero: 417338
#Pedro Lucas Nascmento Pinto / numero: 412692
#Antonio Levy Melo Nogueira / numero: 413230

print('Bem vindo ao conversor, escolha uma opcao e tecle enter!')
a=int(input(' 1 ----- Decimal -> Binario \n 2 ----- Decimal -> Hexadecimal \n 3 ----- Decimal -> Octal \n 4 ----- Binario -> Decimal \n 5 ----- Binario -> Hexadecimal \n 6 ----- Binario -> Octal \n 7 ----- Hexadecimal -> Decimal \n 8 ----- Hexadecimal -> Binario \n 9 ----- Hexadecimal -> Octal \n 10 ----- Octal -> Binario \n 11 ----- Octal -> Decimal \n 12 ----- Octal -> Hexadecimal \n Resposta: '))

l=[]
x=int
n=int

if a == 1:
	indice = int()
	a = int(input('Digite o numero decimal que deseja converter para binario: '))
	r = int()
	l = []
	z = []
	while (a > 0):
		l.append(a%2)
		a = a/2 
	for i in range(len(l)-1,-1,-1):
		z.append(l[i])
	for v in range (len(z)-1,-1,-1):
		r += int(z[v]) * (10**indice)
		indice = indice+1
	print('Esse numero em binario e: '+ str(r))

elif a == 2:
	a = int(input('Diga o numero decimal que deseja converter para hexadecimal: '))
	l = []
	z = []
	v=['A','B','C','D','E','F']

	validador = bool(1)

	while validador:
		if a < 16:
			if a >= 10:
				l.append(v[a-10])
			else:
				l.append(a)
        
			validador = bool(0)
        
		else:
			if (a%16) >= 10:
				l.append(v[(a%16)-10])
			else:
				l.append(a%16)
			a = int(a/16)
	for i in range(len(l)-1,-1,-1):
		z.append(l[i])
	for v in range (len(z)-1,-1,-1):
 		z[v] = str(z[v])
	s=''.join(z[::])
	print('Esse numero em hexadecimal e:',s)

elif a == 3:
	a = int(input('Informe o numero decimal que deseja transformar para octal: '))
	l = []
	while(a>0):
		l.append(str(a%8))
		a = a//8
	s=''.join(l[::-1])
	print('O valor desse numero em octal e: '+ str(s))

elif a == 4:    	
	n=str(input('Informe o numero binario que deseja converter para decimal: '))
	z=[]
	r=0
	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		if z[v] == '1':
			r += int(z[v]) * (2**v)
	print('O valor em decimal e: '+ str(r))

elif a == 5:
	n=str(input('Informe o numero binario que deseja converter para hexadecimal: '))
	z=[]
	r=0
	l = []
	v=['A','B','C','D','E','F']
	validador = bool(1)
	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		if z[v] == '1':
			r += int(z[v]) * (2**v)

	l = []
	z = []
	v=['A','B','C','D','E','F']

	validador = bool(1)

	while validador:
		if r < 16:
			if r >= 10:
				l.append(v[r-10])
			else:
				l.append(r)
	        
			validador = bool(0)
        
		else:
			if (r%16) >= 10:
				l.append(v[(r%16)-10])
			else:
				l.append(r%16)
			r = int(r/16)
	for i in range(len(l)-1,-1,-1):
		z.append(l[i])
	for v in range (len(z)-1,-1,-1):
		z[v] = str(z[v])
	s=''.join(z[::])
	print('Esse numero em hexadecimal e:',s)

elif a == 6:
	n=str(input('Informe o numero binario que deseja converter para octal: '))
	z=[]
	r=0
	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		if z[v] == '1':
			r += int(z[v]) * (2**v)
	
	l = []
	while(r>0):
		l.append(str(r%8))
		r = r//8
	s=''.join(l[::-1])
	print('O valor desse numero em octal e: '+ str(s))
	
elif a ==7:
	n = str(input('Informe o numero Hexadecimal que deseja transformar para decimal: ')).upper()
	z = []
	r = 0
	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		if z[v] == 'A':
			z[v] = '10'
		elif z[v] == 'B':
			z[v] = '11'
		elif z[v] == 'C':
			z[v] = '12'
		elif z[v] == 'D':
			z[v] = '13'
		elif z[v] == 'E':
			z[v] = '14'
		elif z[v] == 'F':
			z[v] = '15'
		r += int(z[v]) * (16**v)
	print('O valor desse numero em decimal e:',r)


elif a == 8:
	n = str(input('Informe o numero Hexadecimal que deseja transformar para binario: ')).upper()
	z = []
	a= int()
	indice = int(0)
	r = int()
	l = []
	b= []
	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		if z[v] == 'A':
			z[v] = '10'
		elif z[v] == 'B':
			z[v] = '11'
		elif z[v] == 'C':
			z[v] = '12'
		elif z[v] == 'D':
			z[v] = '13'
		elif z[v] == 'E':
			z[v] = '14'
		elif z[v] == 'F':
			z[v] = '15'
		r += int(z[v]) * (16**v)

	while (r > 0):
		l.append(r%2)
		r = r/2 
	for i in range(len(l)-1,-1,-1):
		b.append(l[i])
	for v in range (len(b)-1,-1,-1):
		a += int(b[v]) * (10**indice)
		indice = indice+1
	print('Esse numero em binario e: '+ str(a))

elif a == 9:
	n = str(input('Informe o numero Hexadecimal que deseja transformar para octal: ')).upper()
	z = []
	r = 0
	a = int
	indice = int()
	r = int()
	l = []
	z = []
	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		if z[v] == 'A':
			z[v] = '10'
		elif z[v] == 'B':
			z[v] = '11'
		elif z[v] == 'C':
			z[v] = '12'
		elif z[v] == 'D':
			z[v[::-1])
	print('O valor desse numero em octal e: '+ str(s))

elif a == 10:
	n = str(input('Informe o numero octal que deseja converter para binario: '))
	z = []
	l = []
	s =[]
	r = 0
	indice = int()
	a = int()

	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		r += int(z[v]) * (8**v)

	while (r > 0):
		l.append(r%2)
		r = int(r/2) 
	for i in range(len(l)-1,-1,-1):
		s.append(l[i])
	for v in range (len(s)-1,-1,-1):
		a += int(s[v]) * (10**indice)
		indice = indice+1
	print('Esse numero em binario e: '+ str(a))

elif a == 11:
	n =str(input('Informe o numero octal que deseja converter para decimal: '))
	z= []
	r= 0

	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		r += int(z[v]) * (8**v)
	print ('O valor em decimal e: ',r)

elif a == 12:
	n =str(input('Informe o numero octal que deseja converter para hexadecimal: '))
	r = 0
	l = []
	z = []
	a = []

	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		r += int(z[v]) * (8**v)

	validador = bool(1)

	while validador:
		v = ["A","B","C","D","E","F"]
		if r < 16:
			if r >= 10:
				aux = v[r-10]
				l.append(aux)
			else:
				l.append(r)
			validador = bool(0)
        
		else:
			if (r%16) >= 10:
				l.append(v[(r%16)-10])
			else:
				l.append(r%16)
			r = int(r/16)
		
	for i in range(len(l)-1,-1,-1):
		a.append(l[i])
	for v in range (len(a)-1,-1,-1):
		a[v] = str(a[v])
	s=''.join(a[::])
	print('Esse numero em hexadecimal e: ',s)

else:
	print('Essa opcao nao esta disponivel, por favor selecione uma opcao valida!!!')
] = '13'
		elif z[v] == 'E':
			z[v] = '14'
		elif z[v] == 'F':
			z[v] = '15'
		r += int(z[v]) * (16**v)

	while(r>0):
		l.append(str(r%8))
		r = r//8
	s=''.join(l[::-1])
	print('O valor desse numero em octal e: '+ str(s))

elif a == 10:
	n = str(input('Informe o numero octal que deseja converter para binario: '))
	z = []
	l = []
	s =[]
	r = 0
	indice = int()
	a = int()

	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		r += int(z[v]) * (8**v)

	while (r > 0):
		l.append(r%2)
		r = int(r/2) 
	for i in range(len(l)-1,-1,-1):
		s.append(l[i])
	for v in range (len(s)-1,-1,-1):
		a += int(s[v]) * (10**indice)
		indice = indice+1
	print('Esse numero em binario e: '+ str(a))

elif a == 11:
	n =str(input('Informe o numero octal que deseja converter para decimal: '))
	z= []
	r= 0

	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		r += int(z[v]) * (8**v)
	print ('O valor em decimal e: ',r)

elif a == 12:
	n =str(input('Informe o numero octal que deseja converter para hexadecimal: '))
	r = 0
	l = []
	z = []
	a = []

	for i in range (len(n)-1,-1,-1):
		z.append(n[i])
	for v in range (len(z)-1,-1,-1):
		r += int(z[v]) * (8**v)

	validador = bool(1)

	while validador:
		v = ["A","B","C","D","E","F"]
		if r < 16:
			if r >= 10:
				aux = v[r-10]
				l.append(aux)
			else:
				l.append(r)
			validador = bool(0)
        
		else:
			if (r%16) >= 10:
				l.append(v[(r%16)-10])
			else:
				l.append(r%16)
			r = int(r/16)
		
	for i in range(len(l)-1,-1,-1):
		a.append(l[i])
	for v in range (len(a)-1,-1,-1):
		a[v] = str(a[v])
	s=''.join(a[::])
	print('Esse numero em hexadecimal e: ',s)

else:
	print('Essa opcao nao esta disponivel, por favor selecione uma opcao valida!!!')

